<?php
/*
| -------------------------------------------------------------------
| INFOS
| -------------------------------------------------------------------
| This file was autogenerated on 2009-06-08T14:28:59+02:00
|	
|	IFSIC Dev Team (CHEGHAM wassim)

|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Sessions class with encryption
| enabled you MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = "MQfUstz7ZlFG9YAD8fa9DW1AAt64zVQc5iatt02hPDGmDWllXV";
