<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
| -------------------------------------------------------------------
| INFOS
| -------------------------------------------------------------------
| This file was autogenerated on 2009-06-08T14:28:59+02:00
|	
|	IFSIC Dev Team (CHEGHAM wassim)

|--------------------------------------------------------------------------
| Available Languages
|--------------------------------------------------------------------------
|
*/
$config['available_languages']	= array('en' => 'English', 'fr' => 'French');

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'fr';
